// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teapot.DataAccess.Contexts;

#nullable disable

namespace Teapot.DataAccess.Migrations
{
    [DbContext(typeof(Teapot418DbContext))]
    partial class Teapot418DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teapot.Entities.Concrete.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContributerId")
                        .HasColumnType("integer")
                        .HasColumnName("contributer_id");

                    b.Property<int>("ProjectOwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("project_owner_id");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.HasIndex("ContributerId")
                        .HasDatabaseName("ix_chats_contributer_id");

                    b.HasIndex("ProjectOwnerId")
                        .HasDatabaseName("ix_chats_project_owner_id");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer")
                        .HasColumnName("chat_id");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer")
                        .HasColumnName("sender_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_messages_chat_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_messages_sender_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_projects_owner_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.ProjectContributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContributorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contributor_id");

                    b.Property<int>("ContributorId1")
                        .HasColumnType("integer")
                        .HasColumnName("contributor_id1");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("project_id");

                    b.Property<int>("ProjectId1")
                        .HasColumnType("integer")
                        .HasColumnName("project_id1");

                    b.HasKey("Id")
                        .HasName("pk_project_contributor");

                    b.HasIndex("ContributorId1")
                        .HasDatabaseName("ix_project_contributor_contributor_id1");

                    b.HasIndex("ProjectId1")
                        .HasDatabaseName("ix_project_contributor_project_id1");

                    b.ToTable("project_contributor", (string)null);
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.UserProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_projects");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_user_projects_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_projects_user_id");

                    b.ToTable("user_projects", (string)null);
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.Chat", b =>
                {
                    b.HasOne("Teapot.Entities.Concrete.User", "Contributer")
                        .WithMany()
                        .HasForeignKey("ContributerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chats_users_contributer_id");

                    b.HasOne("Teapot.Entities.Concrete.User", "ProjectOwner")
                        .WithMany()
                        .HasForeignKey("ProjectOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chats_users_project_owner_id");

                    b.Navigation("Contributer");

                    b.Navigation("ProjectOwner");
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.Message", b =>
                {
                    b.HasOne("Teapot.Entities.Concrete.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_chats_chat_id");

                    b.HasOne("Teapot.Entities.Concrete.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_sender_id");

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.Project", b =>
                {
                    b.HasOne("Teapot.Entities.Concrete.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.ProjectContributor", b =>
                {
                    b.HasOne("Teapot.Entities.Concrete.User", "Contributor")
                        .WithMany("Projects")
                        .HasForeignKey("ContributorId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_contributor_users_contributor_id1");

                    b.HasOne("Teapot.Entities.Concrete.Project", "Project")
                        .WithMany("Contributers")
                        .HasForeignKey("ProjectId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_contributor_projects_project_id1");

                    b.Navigation("Contributor");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.UserProject", b =>
                {
                    b.HasOne("Teapot.Entities.Concrete.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_projects_projects_project_id");

                    b.HasOne("Teapot.Entities.Concrete.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_projects_users_user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.Project", b =>
                {
                    b.Navigation("Contributers");
                });

            modelBuilder.Entity("Teapot.Entities.Concrete.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
