import "./globals.css";
import { Inter, Space_Mono } from "next/font/google";
import Header from "./_components/Header";

const inter = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={inter.className} lang="en">
      <body>{children}</body>
    </html>
  );
}
