import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./_contexts/AuthContext";
import "./globals.css";
import { Inter, Space_Mono } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Toaster />
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  );
}
